ota-plus-web/app/com/advancedtelematic/auth/garage/LoginAction.scala
ota-plus-web/app/reactapp/src/utils/Common.jsx
ota-plus-web/app/views/main.scala.html

Integration of OIDC providers other then Auth0 is problematic
if logout functionality in ui explicitly calls Auth0. This change
should allow to implement provider-specific logout actions.
Resolves: PRO-4984

Move Auth0 specific logout functionality to server

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/controllers/PathBinders.scala
ota-plus-web/build.sbt
ota-plus-web/test/com/advancedtelematic/api/ApiClientTest.scala
project/Dependencies.scala

Error was that the key type was sent as `{"keyType":"\"RSA\""}` to the services. Added Play thingie to be able to use a circe encoder. Tested on Oslo.

Use Circe to serialize keyType

---

ota-plus-web/build.sbt

App crashes in case openjdk:latest resolves to version 10.
The reason appears to be new modules system and class loading.

Explicitly set base docker image

---

ota-plus-web/app/com/advancedtelematic/api/CryptApi.scala

ota-app was returning valid credentials.zip with invalid autoprov certificate when downloading credentials from another user (hats)
This happens in hat environments. The credentials.zip is still downloaded, but contains 0 length autoprov pkcs12 file.

Return 404 when credentials are not found in crypt

---

ota-plus-web/app/com/advancedtelematic/auth/garage/NoLoginAction.scala
ota-plus-web/app/com/advancedtelematic/controllers/LoginController.scala

After https://github.com/advancedtelematic/ota-plus-user-profile/pull/73 we can't create a new user because decoding the `UserLogin` event expects a new field `namespace` which is not present.

Fix an issue where we cant create a new user

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/auth/oidc/NamespaceProvider.scala
ota-plus-web/app/com/advancedtelematic/controllers/ClientToolController.scala
ota-plus-web/app/com/advancedtelematic/controllers/LoginController.scala
ota-plus-web/app/com/advancedtelematic/controllers/NamespaceController.scala
ota-plus-web/app/com/advancedtelematic/controllers/UserProfileController.scala
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/conf/application.conf
ota-plus-web/conf/routes
ota-plus-web/test/com/advancedtelematic/controllers/ClientToolControllerSpec.scala
ota-plus-web/test/com/advancedtelematic/controllers/GarageLoginSpec.scala
ota-plus-web/test/com/advancedtelematic/controllers/NamespaceControllerSpec.scala
project/Dependencies.scala

Break the constraint that `userId == namespace`. When a new user logs in, we generate a unique namespace different than the userId. When an existing user logs in, we fetch the namespace from user-profile.
Should be merged and deployed with https://github.com/advancedtelematic/ota-plus-user-profile/pull/85.

[OTA-2618] New users get a unique namespace different than the userId

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/controllers/NamespaceController.scala
ota-plus-web/conf/routes

This is so that app can access the new `organization` endpoints from user-profile:
- GET /organization/setup -> GET /api/v1/organization/:current-namespace/setup
- GET /organization/tentative_users -> GET /api/v1/organization/:current-namespace/tentative_users
- POST /organization/users -> GET /api/v1/organization/:current-namespace/users

[OTA-2848] Add routes to latest user-profile organizations endpoints

---

ota-plus-web/app/reactapp/src/stores/SoftwareStore.js

The `receivedAt` field that was used previously exists only in the device-registry DB entry, which is not the thing that device-registry returns via the installation history endpoint.

[OTA-3105] Sort device update history by eventTime field

---

ota-plus-web/build.sbt

sbt refuses to run `release` in tc if we use `-SNAPSHOT`
Signed-off-by: Simão Mata <simao.mata@here.com>

Use -ATS suffix for tracing lib version

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/test/com/advancedtelematic/controllers/NamespaceControllerSpec.scala

Namespace/organization can also come from legacy account name, so it also needs to be URL-encoded.

url-encode namespace in path

---

ota-plus-web/docs/modules/ROOT/pages/_partials/devices.adoc
ota-plus-web/docs/modules/ROOT/pages/create-device-groups.adoc
ota-plus-web/docs/modules/ROOT/pages/create-provisioning-key.adoc
ota-plus-web/docs/modules/ROOT/pages/device-page.adoc

This PR is to clean up some asciidoc syntax issues that were making antora barf up a bunch of warnings (and in some cases errors). That looks ugly on CI, and it also means that it's easy to miss a warning or error that we actually care about.
Mainly there were 3 issues:
This comes from something that's a good practice in Markdown, but a bad habit in asciidoc. In asciidoc, you should either make an ordered list like this:
```
. some item
. something else
. item 3
```
or this:
```
1. some item
2. something else
3. item 3
```
The first option will automatically number the list for you, and you don't have to worry about it. The second option will also auto-number, but if the number you put is different that what got assigned with auto-numbering, it will throw a warning. This is actually good, …

Fix asciidoc syntax issues to clean up warnings

---

ota-plus-web/docs/modules/ROOT/pages/_partials/devices.adoc
ota-plus-web/docs/modules/ROOT/pages/create-device-groups.adoc
ota-plus-web/docs/modules/ROOT/pages/create-provisioning-key.adoc
ota-plus-web/docs/modules/ROOT/pages/index.adoc
ota-plus-web/docs/modules/ROOT/pages/manage-device-prov.adoc

As of Antora 2.1, images and attachments can use the same resourceId syntax as xrefs. This makes our lives easier, and means we no longer have to keep redundant copies of images in all the repos.

DOCS: Use resourceId for images

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/api/ApiClientSupport.scala
ota-plus-web/app/com/advancedtelematic/controllers/Data.scala
ota-plus-web/app/com/advancedtelematic/controllers/FeedController.scala
ota-plus-web/test/com/advancedtelematic/controllers/FeedControllerSpec.scala

We want to show some new data in the "recently created" feed. Namely:
1. for device groups, how many devices are in the group.
1. for campaigns, how many devices where potential targets (i.e. the "processed" field in the campaign stats).
1. for updates, which ECU types are part of the update (i.e. the hardware IDs of all the multi-target updates corresponding to the update).
In all cases it was about enriching the results we already had with some new data fetched from other endpoints. For 3 I had to add a director client to fetch the multi-target updates.

Add extra data to "recently created" endpoint

---

build.sbt
project/Versioning.scala

This reverts commit 3d1ef2761a9426f9caf84a4b85d1cce568bad481.
We still need the old tag format to deploy from GoCD until the Gitlab pipeline is ready. We can reapply this patch once we finish that.

Revert "Only tag releases with HEAD sha"

---

.gitlab-ci.yml

FE devs are still using the old `rome` hat. TC used to build the Docker image from `deploy/rome` but it does it no more.

Build Docker image from branch `deploy/rome`.

---

ota-plus-web/app/reactapp/src/components/profile/ProfileOrganization.jsx

Need some adjustment to show the tentative user emails after https://github.com/advancedtelematic/ota-plus-user-profile/pull/128, because before user-profile was returning
```
[ "a@test.com", "b@test.com" ]
```
but now it's returning
```
[ { email : "a@test.com", addedAt : "1970-01-01T00:00:00Z" } , { email : "b@test.com", addedAt : "1970-01-01T00:00:00Z" } ]
```

Adapt to the new format of the tentative_users endpoint

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/api/clients/UserProfileApi.scala
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/test/com/advancedtelematic/controllers/GarageLoginSpec.scala
ota-plus-web/test/com/advancedtelematic/controllers/OrganizationControllerSpec.scala

After https://github.com/advancedtelematic/ota-plus-user-profile/pull/133 `/user/organizations` will stop sending a `isDefault` flag with the organization details. That flag is kind of legacy and it doesn't make much sense to send it to filter a single organization out. Also removing it will make the BE for that endpoint a bit simpler. FE only needs to know the default on login, we can use a dedicated endpoint for that.

Use new default organization endpoint.

---

ota-plus-web/app/com/advancedtelematic/api/clients/UserProfileApi.scala
ota-plus-web/app/com/advancedtelematic/controllers/FeedController.scala
ota-plus-web/test/com/advancedtelematic/controllers/FeedControllerSpec.scala

We want to show which users were added, evicted or left an
organization in the "recent activity" feed in the new homepage
of the web app.

[OTA-4205] Fetch org membership events for the "recent activity" feed.

---

ota-plus-web/app/com/advancedtelematic/api/clients/UserProfileApi.scala
ota-plus-web/app/com/advancedtelematic/auth/garage/NoLoginAction.scala
ota-plus-web/app/com/advancedtelematic/auth/oidc/NamespaceProvider.scala
ota-plus-web/test/com/advancedtelematic/controllers/GarageNoLoginSpec.scala

The test environments automatically created on EKS rely on a
`default` namespace being available. The `NoLoginAction` will
take care of that so that we can spin test environments. Still
there is no authentication, we just check if the `default`
namespace is available and we created if it's not.

Create default namespace for EKS cluster.

---

ota-plus-web/conf/application.conf

See the bugs OTA-4328 and OTA-4330.
Both are caused by the headers being too big.

[OTA-4328] Increase Play max header size.

---

ota-plus-web/app/com/advancedtelematic/api/OtaPlusConfig.scala
ota-plus-web/app/com/advancedtelematic/controllers/Application.scala
ota-plus-web/app/reactapp/src/components/software/BlacklistModal.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/pages/ImpactAnalysis.jsx
ota-plus-web/app/reactapp/src/stores/ImpactAnalysisStore.js
ota-plus-web/app/reactapp/src/stores/SoftwareStore.js
ota-plus-web/conf/application.conf

This is part of the termination of the ota-core service.
Once https://github.com/advancedtelematic/ota-device-registry/pull/159 is merged and deployed device-registry will take care of the "blacklisting" feature.

[OTA-3654] Route blacklist to device-registry instead of ota-core

---

ota-plus-web/app/com/advancedtelematic/api/clients/UserProfileApi.scala
ota-plus-web/app/com/advancedtelematic/controllers/OrganizationController.scala
ota-plus-web/test/com/advancedtelematic/controllers/OrganizationControllerSpec.scala

This will have the effect the the user will always land on the last
accessed organization, even if he logs out or gets logged out.

[OTA-3955] Update the default organization when switching.

---

ota-plus-web/app/com/advancedtelematic/api/OtaPlusConfig.scala
ota-plus-web/app/com/advancedtelematic/controllers/Application.scala
ota-plus-web/conf/application.conf

Resolver is a service that doesn't exist anymore. This
old routes are not used anymore and can be cleaned up.

Remove unused resolver routes.

---

ota-plus-web/app/com/advancedtelematic/auth/oidc/NamespaceProvider.scala

This class was used when we used to have namespace = userId. But that
is not the case since f1be3c56 (see OTA-2618).
I can't imagine we'll ever want to support this case again, now that we have
the whole organizations/environments logic. Moreover, we're not using
this in any environment: I've checked the old hats, EKS and DEV/SIT/PRD.
So there's no use for this, and we can clean it up.

Remove unused NamespaceFromIdentity.
