advancedtelematic/ota-plus-server

ota-plus-web/app/views/main.scala.html

See 491b8c5a49cadb88a47d113f7ad396aa6bcf71f6

[PRO-4998] Fix logout form in main.scala.html

---

ota-plus-web/app/reactapp/css/pages.scss
ota-plus-web/app/reactapp/src/components/device/properties/List.jsx

@jerrytrieu Something wrong with git formatting. My local files are well formatted but git displays it in bad format. Maybe you now something about this problem?

Device install button redesign

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/controllers/NamespaceSetupController.scala
ota-plus-web/app/com/advancedtelematic/controllers/PathBinders.scala
ota-plus-web/build.sbt
ota-plus-web/conf/routes
ota-plus-web/test/com/advancedtelematic/controllers/NamespaceSetupControllerSpec.scala

Note: Shouldn't break the UI since the setup controller is declared with the new key type option set to "RSA" in the routes file.
Confirmed to work on the Oslo environment.

ATS Garage Ed25519 option

---

ota-plus-web/app/reactapp/src/components/packages/List.jsx
ota-plus-web/app/reactapp/src/components/packages/ListItemVersion.jsx
ota-plus-web/app/reactapp/src/stores/PackagesStore.js

Reverts advancedtelematic/ota-plus-server#1633

Revert "Mocked package/package version delete"

---

ota-plus-web/app/reactapp/src/components/device/Header.jsx
ota-plus-web/app/reactapp/src/stores/DevicesStore.js

Reverts advancedtelematic/ota-plus-server#1632

Revert "Mocked delete device"

---

ota-plus-web/app/reactapp/src/pages/Home.jsx

Reverts advancedtelematic/ota-plus-server#1759

Revert "Hide terms and conditions when ui user profile is off"

---

ota-plus-web/app/assets/js/login.js

Tbh, I am not sure if this will fix the issue, because on my local app instance auth0 widget is loading fast.
Solution taken from here: https://github.com/auth0/lock/issues/1227

Fixed auth0 widget loading too long

---

ota-plus-web/app/reactapp/src/components/campaigns/Wizard.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step4.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step7.jsx
ota-plus-web/app/reactapp/src/components/updates/UpdateDetails.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/Step2.jsx
ota-plus-web/app/reactapp/src/stores/UpdatesStore.js

* additionally complete update's details

[PRO-5532-parent] Debug launch campaign and campaign's data summary 

---

ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step7.jsx
ota-plus-web/app/reactapp/src/components/updates/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/updates/UpdateDetails.jsx
ota-plus-web/app/reactapp/src/stores/UpdatesStore.js

* PRO-5569 reposition foŕm's buttons
* PRO-5570 debug wrong update's details 
* minor refactoring

[PRO-5530-parent] debug managing updates

---

ota-plus-web/app/reactapp/css/_campaign-wizard.scss
ota-plus-web/app/reactapp/src/components/campaigns/Wizard.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step3.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step4.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step5.jsx
ota-plus-web/app/reactapp/src/partials/Sequencer.jsx
ota-plus-web/app/reactapp/src/utils/Collection.jsx

- also debug whether an update item is selected by comparing items' uuid

[OTA-435] Debug stucking steps of campaign wizard

---

ota-plus-web/app/reactapp/src/stores/UpdatesStore.js

[OTA-830] Debug sorting of list of updates

---

ota-plus-web/app/reactapp/src/components/campaigns/Wizard.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step1.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step2.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step3.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step4.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step5.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step6.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step7.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/GroupsList.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/GroupsListItem.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step3Files/SelectUpdateList.jsx

restructure wizard data by remove dependency to step's id

[OTA-840] Refactor wizard's data

---

ota-plus-web/app/reactapp/src/components/campaigns/Wizard.jsx

* metadata as array of paired type and value

[OTA-847] Fix campaign metadata 

---

ota-plus-web/app/reactapp/src/components/updates/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/updates/List.jsx
ota-plus-web/app/reactapp/src/components/updates/ListItem.jsx
ota-plus-web/app/reactapp/src/components/updates/UpdateDetails.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/Step1.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/Step2.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/step2/UpdateDetailList.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/step2/UpdateDetailListItem.jsx

[OTA-873] add missing id tags and fix existing
[OTA-875] drop initial selection if hardware selection was changed
[OTA-369 parent] refactor wizard's data by removing dependency to step's id

[OTA-369-parent] fix update creation

---

ota-plus-web/app/reactapp/css/_campaign-wizard.scss
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/GroupsListItem.jsx

[OTA-701] MockUp for the dynamic campaign in the campaign wizard
[OTA-1009] Smart group icons in the campaign wizard

[OTA-701] & [OTA-1009]

---

ota-plus-web/app/assets/contracts/tc/2018-01/en/terms_conditions.html
ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/views/accountConfirmation.scala.html
ota-plus-web/app/views/activated.scala.html
ota-plus-web/app/views/authorizationError.scala.html

Re-creation of #1846, with new branch name.

OTA-1027 Update support email address

---

ota-plus-web/app/reactapp/src/components/device/hardware/Overlay.jsx
ota-plus-web/app/reactapp/src/stores/HardwareStore.js

rendering hardware/packages tabs even if system_info is not available

[OTA-1532] - displaying packages in DDV modal

---

ota-plus-web/app/reactapp/src/components/device/OverviewPanel.jsx
ota-plus-web/app/reactapp/src/containers/Device.jsx

when you are in Overview, land in Approval if not empty, otherwise land in Queue, otherwise land in History

OTA-1539-choosing activeTab in DDV based on conditions

---

ota-plus-web/app/reactapp/.eslintrc.json
ota-plus-web/app/reactapp/src/components/campaign/SubHeader.jsx
ota-plus-web/app/reactapp/src/components/campaigns/CampaignSummary.jsx
ota-plus-web/app/reactapp/src/components/campaigns/List.jsx
ota-plus-web/app/reactapp/src/components/campaigns/StatisticsDetails.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step3Files/SelectUpdateList.jsx
ota-plus-web/app/reactapp/src/components/updates/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/Step1.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/partials/DependenciesModal.jsx
ota-plus-web/app/reactapp/src/partials/Dropdown.jsx
ota-plus-web/app/reactapp/src/partials/DropdownMenu.jsx
ota-plus-web/app/reactapp/src/partials/EditCampaignModal.jsx
ota-plus-web/app/reactapp/src/partials/index.js
ota-plus-web/app/reactapp/src/partials/lists/SelectableList.jsx
ota-plus-web/app/reactapp/src/stores/CampaignsStore.js
ota-plus-web/app/reactapp/src/utils/AsyncStatusCallbackHandler.jsx
ota-plus-web/app/reactapp/src/utils/Helpers.jsx
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss

[OTA-1955] refactor and fix campaign's components after migration

---

ota-plus-web/app/com/advancedtelematic/auth/oidc/OidcGateway.scala
ota-plus-web/conf/application.conf

Signed-off-by: Shaun Taheri <shaun.taheri@here.com>

Toggle OIDC basic auth header

---

ota-plus-web/app/reactapp/src/Routes.jsx
ota-plus-web/app/reactapp/src/containers/Home.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/partials/Dropdown.jsx
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss

Reverts advancedtelematic/ota-plus-server#1900

Revert "[OTA-1690] fix broken create links in dashboard's Dropdown's"

---

ota-plus-web/app/reactapp/src/stores/PackagesStore.js

Signed-off-by: Binh Hoang <son.binh.hoang@meelogic.com>

[OTA-2185] remove misleading legacy expression

---

ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx
ota-plus-web/app/reactapp/src/components/campaigns/StatisticsDetails.jsx

Update strings to match the mockup

[OTA-2229] update strings

---

ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-2229] minor rewording

---

ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-2322] fix navbar wrapping to a new line

---

ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx
ota-plus-web/app/reactapp/src/components/campaigns/CampaignSummary.jsx
ota-plus-web/app/reactapp/src/components/home/LatestCreatedCampaignItem.jsx
ota-plus-web/app/reactapp/src/stores/CampaignsStore.js

[OTA-2234] new campaign stats structure

---

ota-plus-web/app/reactapp/src/components/device/history/MtuListItem.jsx

See https://github.com/advancedtelematic/director/pull/160
Signed-off-by: Jerry Trieu <jerry.trieu@here.com>

Use eventTime for receivedAt in device-update-history

---

ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-2322] fix navbar flickering

---

ota-plus-web/build.sbt

Signed-off-by: Jochen Schneider <j.schneider@here.com>

Don't upgrade to the latest version which has some issues currently

---

ota-plus-web/app/reactapp/style/ota-default/common.scss

Fix right nav overlapping

---

ota-plus-web/app/reactapp/src/partials/Navigation.jsx

Align names with id locators

---

ota-plus-web/build.sbt

`FROM node:10-alpine`
```
v10.14.2
6.4.1
```
Signed-off-by: Jerry Trieu <jerry.trieu@here.com>

Use advancedtelematic/webpack:10

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/build.sbt

Signed-off-by: Jerry Trieu <jerry.trieu@here.com>

Fix runWebpack sh command and inotify version

---

ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx

New failures export endpoint

---

ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx
ota-plus-web/app/reactapp/src/components/campaigns/CampaignSummary.jsx
ota-plus-web/app/reactapp/src/components/campaigns/StatisticsDetails.jsx
ota-plus-web/app/reactapp/src/components/dashboard/LatestCreatedCampaignItem.jsx
ota-plus-web/app/reactapp/src/stores/CampaignsStore.js

Rework stats in campaign detail view

---

ota-plus-web/app/reactapp/src/components/software/stats/VersionsStats.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/partials/Dropdown.jsx

[OTA-2131] Fix app crash while adding/deleting software

---

ota-plus-web/app/reactapp/src/Routes.jsx
ota-plus-web/app/reactapp/src/containers/Terms.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/pages/TermsAndConditions.jsx
ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/app/reactapp/src/stores/data/newFeatures.js

[OTA-2388] & [OTA-2500] GetStarted adjustments + T&C fix

---

ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx
ota-plus-web/app/reactapp/src/components/campaigns/StatisticsDetails.jsx
ota-plus-web/app/reactapp/src/constants/index.js
ota-plus-web/app/reactapp/src/stores/CampaignsStore.js

[OTA-2233] Retry improvements + StatisticsBar fix

---

ota-plus-web/app/reactapp/src/components/software/ListItemVersion.jsx
ota-plus-web/app/reactapp/src/containers/Software.jsx
ota-plus-web/app/reactapp/src/partials/DependenciesModal.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-2433] Fix DependenciesManager not displaying properly

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json

[OTA-2546] Exact antd version

---

ota-plus-web/app/reactapp/src/partials/TabNavigation.jsx
ota-plus-web/app/reactapp/style/ota-default/pages/_page-software-repository.scss

[OTA-2436] & [OTA-2380] minor fixes

---

ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step3.jsx
ota-plus-web/app/reactapp/src/components/updates/UpdateDetails.jsx
ota-plus-web/app/reactapp/src/pages/Updates.jsx

[OTA-1530] Verify displaying correct data

---

ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx

[OTA-2233] Can't export while 'waiting'

---

ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step7.jsx
ota-plus-web/app/reactapp/src/components/updates/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/updates/UpdateDetails.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/step2/UpdatesWizardDetailList.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/step2/UpdatesWizardDetailListItem.jsx
ota-plus-web/app/reactapp/src/partials/FormSelect.jsx
ota-plus-web/app/reactapp/src/stores/UpdatesStore.js
ota-plus-web/app/reactapp/style/ota-default/modals.scss

[OTA-2381] Update from any software version

---

ota-plus-web/app/reactapp/src/stores/DevicesStore.js
ota-plus-web/app/reactapp/style/ota-default/pages/_page-devices.scss

[OTA-2108] Fix conflicting restrictions

---

ota-plus-web/app/reactapp/src/stores/DevicesStore.js

[OTA-2515] & [OTA-2368] Fix duplicated devices

---

ota-plus-web/app/reactapp/src/components/updates/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/step2/UpdatesWizardDetailListItem.jsx
ota-plus-web/app/reactapp/style/ota-default/modals.scss

[OTA-2381] Update from any improvements

---

ota-plus-web/app/reactapp/src/components/software/CreateModal.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-614] Software CreateModal rework

---

ota-plus-web/app/reactapp/src/components/updates/createWizard/step2/UpdatesWizardDetailListItem.jsx

[OTA-2381] string tweak

---

ota-plus-web/app/reactapp/.eslintrc.json
ota-plus-web/app/reactapp/src/components/campaigns/CampaignSummary.jsx
ota-plus-web/app/reactapp/src/components/campaigns/ContentPanel.jsx
ota-plus-web/app/reactapp/src/components/campaigns/List.jsx
ota-plus-web/app/reactapp/src/components/campaigns/ListHeader.jsx
ota-plus-web/app/reactapp/src/components/campaigns/ListItem.jsx
ota-plus-web/app/reactapp/src/components/campaigns/StatisticsDetails.jsx
ota-plus-web/app/reactapp/src/components/dashboard/LatestCreatedCampaignItem.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/helpers/campaignHelper.js
ota-plus-web/app/reactapp/src/partials/TabNavigation.jsx
ota-plus-web/app/reactapp/src/stores/CampaignsStore.js
ota-plus-web/app/reactapp/src/stores/DevicesStore.js
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss

[OTA-2467] (FE) clean up the campaign page

---

ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step6.jsx
ota-plus-web/app/reactapp/src/partials/Sequencer.jsx

[OTA-1530] Fix campaign wizard

---

ota-plus-web/app/reactapp/.babelrc
ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/reactapp/src/partials/NavigationPopover.jsx
ota-plus-web/app/reactapp/src/partials/NavigationProfile.jsx
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss

[OTA-2604] (FE) See the organisation ID under the profile name

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/api/ApiClientSupport.scala
ota-plus-web/app/com/advancedtelematic/api/DeviceMetadata.scala
ota-plus-web/app/com/advancedtelematic/auth/garage/Auth0Api.scala
ota-plus-web/app/com/advancedtelematic/auth/garage/NoLoginAction.scala
ota-plus-web/app/com/advancedtelematic/auth/oidc/LoginAction.scala
ota-plus-web/app/com/advancedtelematic/auth/oidc/OidcGateway.scala
ota-plus-web/app/com/advancedtelematic/auth/oidc/TokenIntrospection.scala
ota-plus-web/app/com/advancedtelematic/controllers/Application.scala
ota-plus-web/app/com/advancedtelematic/controllers/LoginController.scala
ota-plus-web/app/com/advancedtelematic/controllers/UserProfileController.scala

The build log is polluted by many warnings of unused imports and methods.

Fix some warnings

---

ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss

[OTA-2634] Nav bar not aligning org name correctly (element overlap)

---

ota-plus-web/app/reactapp/src/stores/DevicesStore.js

[OTA-2647] & [OTA-2108] nameContains instead of regex

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json
ota-plus-web/app/reactapp/src/components/software/Header.jsx
ota-plus-web/app/reactapp/src/components/software/List.jsx
ota-plus-web/app/reactapp/src/components/updates/Header.jsx
ota-plus-web/app/reactapp/src/components/updates/List.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/containers/Updates.jsx
ota-plus-web/app/reactapp/src/stores/CampaignsStore.js
ota-plus-web/app/reactapp/src/stores/UpdatesStore.js
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-updates.scss

[OTA-2468] clean up the other pages

---

ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step6.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step7.jsx
ota-plus-web/app/reactapp/src/components/updates/UpdateDetails.jsx
ota-plus-web/app/reactapp/src/constants/index.js
ota-plus-web/app/reactapp/src/helpers/updateDetailsHelper.js
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-2636] Correct software version info

---

ota-plus-web/app/reactapp/src/stores/DevicesStore.js

[OTA-2468] Clean up the other pages 2

---

ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step7.jsx

[OTA-2636] Fix campaign wizard summary

---

ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx
ota-plus-web/app/reactapp/src/components/campaigns/RetryModal.jsx

[OTA-2650] Switch retry from alpha to all

---

ota-plus-web/app/reactapp/src/components/campaign/SubHeader.jsx
ota-plus-web/app/reactapp/src/components/campaigns/Header.jsx
ota-plus-web/app/reactapp/src/components/campaigns/Wizard.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step2.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/GroupsListItem.jsx
ota-plus-web/app/reactapp/src/components/device/Header.jsx
ota-plus-web/app/reactapp/src/components/device/approvalPending/MtuList.jsx
ota-plus-web/app/reactapp/src/components/device/history/MtuList.jsx
ota-plus-web/app/reactapp/src/components/device/properties/List.jsx
ota-plus-web/app/reactapp/src/components/device/queue/MtuList.jsx
ota-plus-web/app/reactapp/src/components/devices/ContentPanel.jsx
ota-plus-web/app/reactapp/src/components/devices/Item.jsx
ota-plus-web/app/reactapp/src/components/updates/CreateModal.jsx
ota-plus-web/app/reactapp/src/containers/Dashboard.jsx
ota-plus-web/app/reactapp/src/containers/Updates.jsx
ota-plus-web/app/reactapp/src/partials/EditCampaignModal.jsx
ota-plus-web/app/reactapp/src/stores/data/newFeatures.js
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-devices.scss

[OTA-2577] Fix unclear or inaccurate wording

---

ota-plus-web/app/reactapp/src/components/devices/ContentPanelSubheader.jsx
ota-plus-web/app/reactapp/src/components/groups/createWizard/step2/Filter.jsx

[OTA-2583] Filtering devices on inaccurate positions

---

ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step7.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/GroupsListItem.jsx
ota-plus-web/app/reactapp/src/stores/GroupsStore.js

Signed-off-by: Jerry Trieu <jerry.trieu@here.com>

Fix group devices count in campaign-wizard

---

ota-plus-web/app/reactapp/src/components/devices/ContentPanel.jsx
ota-plus-web/app/reactapp/src/constants/index.js
ota-plus-web/app/reactapp/src/containers/Devices.jsx

[OTA-2577] Update no ungrouped devices strings

---

ota-plus-web/app/reactapp/src/Routes.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/pages/Dashboard.jsx

[OTA-2722] Don't call /user API when toggleUserProfileMenu is false

---

ota-plus-web/app/reactapp/src/constants/index.js
ota-plus-web/app/reactapp/src/utils/WebsocketHandler.js

[OTA-2660] Fix event-related display issues in campaign view

---

ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/partials/NavigationPopover.jsx
ota-plus-web/app/reactapp/src/stores/UserStore.js

[OTA-2701] User sees ODN equals 'MC's Organization

---

ota-plus-web/app/assets/img/icons/link_button.svg
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/reactapp/src/partials/NavigationProfile.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-2656] Add expandable support sidebar

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json
ota-plus-web/app/reactapp/src/components/devices/Item.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/constants/httpCodes.js
ota-plus-web/app/reactapp/src/constants/pathConstants.js
ota-plus-web/app/reactapp/src/partials/NavigationPopover.jsx
ota-plus-web/app/reactapp/src/partials/NavigationProfile.jsx
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/app/reactapp/src/utils/Common.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss

[OTA-2619] Dropdown with organizations the user can switch to

Feat/ota 2619/user switch organizations

---

ota-plus-web/app/reactapp/src/components/device/Header.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/constants/httpCodes.js
ota-plus-web/app/reactapp/src/constants/index.js
ota-plus-web/app/reactapp/src/containers/Device.jsx
ota-plus-web/app/reactapp/src/helpers/deviceHelper.js
ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/reactapp/src/partials/SupportMenu.jsx
ota-plus-web/app/reactapp/src/stores/DevicesStore.js
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-2800] Handle different http status codes in DDV

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json
ota-plus-web/app/reactapp/src/Routes.jsx
ota-plus-web/app/reactapp/src/components/profile/Header.jsx
ota-plus-web/app/reactapp/src/components/profile/ProfileOrganization.jsx
ota-plus-web/app/reactapp/src/components/profile/index.js
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/partials/NavigationProfile.jsx
ota-plus-web/app/reactapp/src/partials/SearchBar.jsx
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-profile.scss

[OTA-2700] Adding another registered user to user's current organization

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json

[OTA-2830] Bump axios version

---

ota-plus-web/app/reactapp/.eslintrc.json
ota-plus-web/app/reactapp/src/components/profile/ProfileOrganization.jsx
ota-plus-web/app/reactapp/src/partials/NavigationPopover.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-profile.scss

[OTA-2700] Adding another registered user to user's current organization

Feat/ota 2700/adding user to organization

---

ota-plus-web/app/reactapp/src/components/profile/EditOrganizationNameModal.jsx
ota-plus-web/app/reactapp/src/components/profile/ProfileOrganization.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-profile.scss
ota-plus-web/conf/routes

[OTA-2871] User can edit their ODN

Feat/ota 2871/user can edit odn

---

ota-plus-web/app/reactapp/src/stores/DevicesStore.js
ota-plus-web/app/reactapp/src/stores/SoftwareStore.js

To be merged and deployed with https://github.com/advancedtelematic/ota-device-registry/pull/95.

Use 'nameContains' instead of 'regex' as search parameter.

---

ota-plus-web/app/reactapp/src/components/campaigns/ContentPanel.jsx
ota-plus-web/app/reactapp/src/components/software/List.jsx
ota-plus-web/app/reactapp/src/containers/Software.jsx
ota-plus-web/app/reactapp/src/containers/Updates.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/partials/LegalInfoFooter.js
ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/reactapp/src/partials/index.js
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-campaigns.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-dashboard.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-device.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-devices.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-fireworks.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-impact-analysis.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-policy.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-profile.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-software-repository.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-updates.scss
ota-plus-web/app/reactapp/style/ota-default/variables-ota.scss

[OTA-2927] User can access legal info in the footer

[OTA-2927] User can access legal info in the footer

---

ota-plus-web/app/reactapp/src/components/profile/Header.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/pages/Profile.jsx
ota-plus-web/app/reactapp/src/partials/NavigationProfile.jsx
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/override-ant.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-profile.scss

[OTA-2932] Mark organization as alpha

---

ota-plus-web/app/reactapp/src/partials/LegalInfoFooter.js
ota-plus-web/app/reactapp/style/ota-default/pages/_page-device.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-profile.scss

[OTA-3079] Footer disappears in DDV

---

ota-plus-web/app/reactapp/src/partials/NavigationPopover.jsx

[OTA-3083] Fix UserProfile menu not closing after navigation

---

ota-plus-web/app/reactapp/src/components/campaigns/ContentPanel.jsx
ota-plus-web/app/reactapp/src/components/updates/Header.jsx
ota-plus-web/app/reactapp/src/containers/Updates.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-campaigns.scss

[OTA-3078] Fix empty page views

---

ota-plus-web/app/reactapp/src/containers/Terms.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/pages/Dashboard.jsx
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-3082] Footer breaks T&C

---

ota-plus-web/app/reactapp/src/components/software/Header.jsx
ota-plus-web/app/reactapp/src/containers/Software.jsx

[OTA-3081] Software packages tab-bar mis-aligned on alpha account

---

ota-plus-web/app/reactapp/style/ota-default/_campaign-wizard.scss

[OTA-3106] Fix updates divider width on ubuntu

---

ota-plus-web/app/reactapp/src/components/campaign/SubHeader.jsx
ota-plus-web/app/reactapp/src/components/device/Header.jsx
ota-plus-web/app/reactapp/src/components/device/approvalPending/MtuListItem.jsx
ota-plus-web/app/reactapp/src/components/device/queue/MtuListItem.jsx
ota-plus-web/app/reactapp/src/components/groups/ListItem.jsx
ota-plus-web/app/reactapp/src/components/groups/RenameModal.jsx
ota-plus-web/app/reactapp/src/components/profile/EditProfile.jsx
ota-plus-web/app/reactapp/src/components/profile/ProfileOrganization.jsx
ota-plus-web/app/reactapp/src/containers/Devices.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-2805] Standardize rename

---

ota-plus-web/app/reactapp/src/components/profile/access-keys/ListItem.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/stores/ProvisioningStore.js

[OTA-2123] Handle provisioning download errors

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/src/components/campaigns/ContentPanel.jsx
ota-plus-web/app/reactapp/src/components/updates/Header.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/containers/Updates.jsx

[OTA-3141] Campaign List displaying incorrect information

---

ota-plus-web/app/reactapp/src/components/campaigns/StatisticsDetails.jsx

[BUGFIX] Campaigns page texts update

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json
ota-plus-web/app/reactapp/src/components/devices/ContentPanel.jsx
ota-plus-web/app/reactapp/src/stores/DevicesStore.js

[OTA-3155] Scrolling large groups of devices leads to blank screen

---

ota-plus-web/app/reactapp/src/stores/DevicesStore.js

[OTA-3113] Empty black screens instead of DDV

---

ota-plus-web/conf/logback.xml
project/Dependencies.scala

Signed-off-by: Ivan Kliuk <ext-ivan.kliuk@here.com>

[OTA-2957] Add libats-logging

---

ota-plus-web/app/reactapp/src/components/devices/Item.jsx
ota-plus-web/app/reactapp/src/partials/EditModal.jsx

[OTA-3228] Fix device rename modal

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/dashboard/LastDevicesItem.jsx
ota-plus-web/app/reactapp/src/components/dashboard/NoItems.jsx
ota-plus-web/app/reactapp/src/components/device/Header.jsx
ota-plus-web/app/reactapp/src/components/devices/Item.jsx
ota-plus-web/app/reactapp/src/constants/deviceConstants.js
ota-plus-web/app/reactapp/src/constants/index.js
ota-plus-web/app/reactapp/src/containers/Dashboard.jsx
ota-plus-web/app/reactapp/src/partials/Navigation.jsx

[OTA-3074] Texts reorganisation - dashboard

---

ota-plus-web/app/reactapp/src/components/device/HardwarePanel.jsx
ota-plus-web/app/reactapp/src/components/device/InstallationEvents.jsx
ota-plus-web/app/reactapp/src/components/device/hardware/PublicKeyPopover.jsx
ota-plus-web/app/reactapp/src/components/device/software/List.jsx
ota-plus-web/app/reactapp/src/components/groups/RenameModal.jsx
ota-plus-web/app/reactapp/src/components/profile/access-keys/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/software/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/software/EditCommentModal.jsx
ota-plus-web/app/reactapp/src/components/updates/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/Step2.jsx
ota-plus-web/app/reactapp/src/components/updates/createWizard/step2/UpdatesWizardDetailListItem.jsx
ota-plus-web/app/reactapp/src/partials/FormSelect.jsx
ota-plus-web/app/reactapp/src/partials/SizeVerify.jsx

[OTA-3229] & [OTA-3230] & [OTA-3232] & fix blank ddv

---

ota-plus-web/app/reactapp/src/constants/index.js
ota-plus-web/app/reactapp/src/utils/WebsocketHandler.js

[OTA-2249] Fix new devices appearing in currently opened group

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/groups/CreateModal.jsx
ota-plus-web/app/reactapp/src/components/groups/createWizard/step2/CreateClassicGroup.jsx
ota-plus-web/app/reactapp/src/constants/groupConstants.js
ota-plus-web/app/reactapp/style/ota-default/modals.scss

[OTA-3263] Creating group with TXT file - improvements

---

ota-plus-web/app/reactapp/src/utils/WebsocketHandler.js

[OTA-3189] WebSocket security

---

ota-plus-web/build.sbt

[OTA-3320] Update Alpine version

---

ota-plus-web/app/reactapp/src/components/software/CreateModal.jsx
ota-plus-web/app/reactapp/src/partials/OperationCompletedInfo.jsx

[OTA-3393] Upload packages gives error

---

ota-plus-web/app/reactapp/src/components/devices/Item.jsx
ota-plus-web/app/reactapp/src/constants/groupConstants.js

[OTA-3289] In Device Groups, the devices cannot be dragged out properly

---

ota-plus-web/app/reactapp/src/components/device/approvalPending/MtuList.jsx
ota-plus-web/app/reactapp/src/components/device/queue/MtuList.jsx

[OTA-3392] Superfluous text on empty queue/consent

---

ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-3412] Provisioning text is blanked out

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/controllers/PathBinders.scala
ota-plus-web/app/com/advancedtelematic/controllers/ProvisioningController.scala

Signed-off-by: Jochen Schneider <j.schneider@here.com>

URL-encode namespace in ProvisioningController

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json

[OTA-3397] Bump lodash version to 4.17.13 or later

---

ota-plus-web/app/reactapp/src/components/profile/access-keys/NoKeys.jsx
ota-plus-web/app/reactapp/src/components/updates/Header.jsx
ota-plus-web/app/reactapp/src/containers/Provisioning.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-3412] Provisioning text is blanked out - new fixes

---

ota-plus-web/app/reactapp/src/components/device/queue/MtuList.jsx
ota-plus-web/app/reactapp/src/components/device/queue/MtuListItem.jsx
ota-plus-web/app/reactapp/src/utils/WebsocketHandler.js

[OTA-3395] Toggle queue cancel button

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/campaign/InstallationReportView.jsx
ota-plus-web/app/reactapp/src/components/campaigns/CampaignSummary.jsx
ota-plus-web/app/reactapp/src/components/campaigns/Header.jsx
ota-plus-web/app/reactapp/src/components/campaigns/List.jsx
ota-plus-web/app/reactapp/src/components/campaigns/ListHeader.jsx
ota-plus-web/app/reactapp/src/components/campaigns/RetryModal.jsx
ota-plus-web/app/reactapp/src/components/campaigns/StatisticsDetails.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step1.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step2.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step3.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step4.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step5.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step6.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step7.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/GroupsList.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/GroupsListItem.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/OLPGroupsListItem.jsx
ota-plus-web/app/reactapp/src/components/device/queue/MtuListItem.jsx
ota-plus-web/app/reactapp/src/partials/DependenciesModal.jsx
ota-plus-web/app/reactapp/src/utils/Common.jsx
ota-plus-web/app/reactapp/src/utils/WebsocketHandler.js

[OTA-3162] Texts reorganisation - campaigns

---

ota-plus-web/app/assets/locales/en/translation.json

[OTA-3385] Rename 'last seen online' with 'last checked for update'

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/dashboard/LastDevices.jsx
ota-plus-web/app/reactapp/src/components/dashboard/LastSoftware.jsx
ota-plus-web/app/reactapp/src/components/dashboard/LatestCreatedCampaigns.jsx
ota-plus-web/app/reactapp/src/components/dashboard/NoItems.jsx
ota-plus-web/app/reactapp/src/constants/urlConstants.js
ota-plus-web/app/reactapp/style/ota-default/common.scss

[OTA-3415 & OTA-3418 & OTA-3225] Minor renaming

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/groups/createWizard/step2/CreateClassicGroup.jsx
ota-plus-web/app/reactapp/src/constants/urlConstants.js
ota-plus-web/app/reactapp/style/ota-default/modals.scss

[OTA-3296] Message for VIN list imports in Fixed groups

---

ota-plus-web/app/com/advancedtelematic/controllers/Application.scala

Goes with https://github.com/advancedtelematic/web-events/pull/24.

[OTA-3479] Use the right namespace to authenticate to the web socket service

---

ota-plus-web/app/reactapp/src/components/devices/ContentPanelSubheader.jsx

[OTA-2837] Fix smart groups displaying incorrect filters

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/campaigns/ContentPanel.jsx
ota-plus-web/app/reactapp/src/components/groups/createWizard/step2/CreateClassicGroup.jsx
ota-plus-web/app/reactapp/src/components/profile/AccessKeys.jsx
ota-plus-web/app/reactapp/src/components/profile/access-keys/Header.jsx
ota-plus-web/app/reactapp/src/components/profile/access-keys/NoKeys.jsx
ota-plus-web/app/reactapp/src/containers/Provisioning.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/pages/_page-profile.scss
ota-plus-web/app/reactapp/style/ota-default/variables-ota.scss

[OTA-3112] Standardize the pages with no info yet

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/devices/Item.jsx
ota-plus-web/app/reactapp/src/containers/Dashboard.jsx

[OTA-3567] Additional instances of wording changes

---

ota-plus-web/app/reactapp/src/components/software/ListItemVersion.jsx

[OTA-3596] Blank page displayed when accessing software versions

---

ota-plus-web/app/reactapp/src/constants/urlConstants.js
ota-plus-web/app/reactapp/src/partials/SupportMenu.jsx

[OTA-3597] (FE) Fix docs link in OTA Connect UI

---

ota-plus-web/app/reactapp/src/components/devices/Item.jsx
ota-plus-web/app/reactapp/src/containers/Devices.jsx

Devices cannot be dragged out properly in small Device Fixed Groups

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/campaigns/Wizard.jsx
ota-plus-web/app/reactapp/src/constants/campaignErrorCodes.js

Display error message when trying to create a campaign without devices

---

ota-plus-web/app/reactapp/src/components/profile/access-keys/ListItem.jsx
ota-plus-web/app/reactapp/src/constants/httpCodes.js
ota-plus-web/app/reactapp/src/stores/ProvisioningStore.js
ota-plus-web/app/reactapp/style/ota-default/pages/_page-profile.scss

[OTA-3104] Handle /user/setup response properly

---

ota-plus-web/app/reactapp/src/constants/urlConstants.js
ota-plus-web/app/reactapp/src/partials/SupportMenu.jsx

Adding upated locations for outdated doc URLs

fixing doc URLs

---

ota-plus-web/app/reactapp-new/package-lock.json
ota-plus-web/app/reactapp-new/package.json
ota-plus-web/app/reactapp-new/src/App.tsx
ota-plus-web/app/reactapp-new/src/Routes.tsx
ota-plus-web/app/reactapp-new/src/index.tsx

[OTA-3670] Basic react-router setup

---

ota-plus-web/app/reactapp-new/.babelrc
ota-plus-web/app/reactapp-new/package-lock.json
ota-plus-web/app/reactapp-new/package.json
ota-plus-web/app/reactapp-new/src/App.tsx
ota-plus-web/app/reactapp-new/src/index.tsx
ota-plus-web/app/reactapp-new/src/networking/UserNetworking.ts
ota-plus-web/app/reactapp-new/src/saga/rootSaga.ts
ota-plus-web/app/reactapp-new/src/saga/userSaga.ts
ota-plus-web/app/reactapp-new/src/store/index.ts
ota-plus-web/app/reactapp-new/src/store/user/actions.ts
ota-plus-web/app/reactapp-new/src/store/user/reducers.ts
ota-plus-web/app/reactapp-new/src/store/user/types.ts
ota-plus-web/app/reactapp-new/tslint.json

(Tech) Redux setup

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/auth/oidc/NamespaceProvider.scala
ota-plus-web/app/reactapp/src/stores/UserStore.js
ota-plus-web/test/com/advancedtelematic/controllers/GarageLoginSpec.scala
ota-plus-web/test/com/advancedtelematic/controllers/NamespaceControllerSpec.scala

To be merged with https://github.com/advancedtelematic/ota-plus-user-profile/pull/104.

[OTA-3326] Read `isDefault` flag instead of `isCreator`.

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/src/components/profile/access-keys/List.jsx
ota-plus-web/app/reactapp/src/components/profile/access-keys/ListItem.jsx
ota-plus-web/app/reactapp/src/stores/ProvisioningStore.js
ota-plus-web/app/reactapp/src/stores/UserStore.js

[OTA-3104 & OTA-3644] Handle account setup status for prov-keys + bump eslint-utils ver

---

ota-plus-web/app/reactapp-new/.gitignore
ota-plus-web/app/reactapp-new/package-lock.json
ota-plus-web/app/reactapp-new/package.json
ota-plus-web/app/reactapp-new/src/App.spec.tsx
ota-plus-web/app/reactapp-new/src/App.tsx
ota-plus-web/app/reactapp-new/src/__mocks__/fileMock.js
ota-plus-web/app/reactapp-new/src/store/index.ts
ota-plus-web/app/reactapp-new/testsSetup.ts

OTA-3661
(Tech) Unit tests setup
OTA-3662
(Tech) Code Coverage
Also configured redux devtools.

OTA-3661-3622 Unit tests setup

---

ota-plus-web/app/assets/locales/en/translation-new.json
ota-plus-web/app/reactapp-new/.babelrc
ota-plus-web/app/reactapp-new/package-lock.json
ota-plus-web/app/reactapp-new/src/components/common/ExternalLink.tsx
ota-plus-web/app/reactapp-new/src/components/layout/AppFooter.tsx
ota-plus-web/app/reactapp-new/style/index.scss
ota-plus-web/app/reactapp-new/webpack.dev.js
ota-plus-web/app/reactapp-new/webpack.prod.js

[OTA-3755] Add footer

---

ota-plus-web/app/reactapp-new/src/networking/AxiosConnector.ts
ota-plus-web/app/reactapp-new/src/networking/UrlBuilder.spec.tsx
ota-plus-web/app/reactapp-new/src/networking/UrlBuilder.ts
ota-plus-web/app/reactapp-new/src/networking/UserNetworking.ts
ota-plus-web/app/reactapp-new/src/utils/types.ts

Signed-off-by: Lukasz Aniszewski <aniszew.luk@ad.meelogic.com>

Created axios setup

---

ota-plus-web/app/assets/locales/en/translation-new.json
ota-plus-web/app/reactapp-new/package-lock.json
ota-plus-web/app/reactapp-new/src/components/Account/AccountSettings.tsx
ota-plus-web/app/reactapp-new/src/components/Account/index.tsx
ota-plus-web/app/reactapp-new/src/components/DocsLinks/DocsLinks.tsx
ota-plus-web/app/reactapp-new/src/components/common/Icon.tsx
ota-plus-web/app/reactapp-new/src/components/layout/AppNavbar.tsx
ota-plus-web/app/reactapp-new/src/constants/styleConstants.ts
ota-plus-web/app/reactapp-new/src/styled.d.ts
ota-plus-web/app/reactapp-new/src/theme.ts
ota-plus-web/app/reactapp-new/src/utils/stringUtils.ts
ota-plus-web/app/reactapp-new/style/index.scss

Signed-off-by: Lukasz Aniszewski <aniszew.luk@ad.meelogic.com>

[OTA-3785] Created profile slider

---

ota-plus-web/app/com/advancedtelematic/api/ApiClient.scala
ota-plus-web/app/com/advancedtelematic/auth/oidc/NamespaceProvider.scala
ota-plus-web/test/com/advancedtelematic/controllers/GarageLoginSpec.scala

To be merged with https://github.com/advancedtelematic/ota-plus-user-profile/pull/106.

[OTA-3739] Refactor login process.

---

ota-plus-web/app/reactapp-new/src/components/Account/AccountSettings.tsx

Signed-off-by: Lukasz Aniszewski <aniszew.luk@ad.meelogic.com>

[OTA-3785] Create profile slider BUGFIX

---

sbt

Update local copy of ./sbt script to the latest master from
https://github.com/paulp/sbt-extras (aa4425cc96aee5119fb9fee9138b3d3bdb6482f7)
to fix problems with gitlab pipeline.

Update ./sbt script to latest master

---

ota-plus-web/app/reactapp/src/components/campaign/CancelCampaignModal.jsx
ota-plus-web/app/reactapp/src/partials/TabNavigation.jsx

[OTA-3753] Empty campaign page is displayed after cancelling campaign

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json
ota-plus-web/app/reactapp/src/components/profile/ProfileOrganization.jsx

[OTA-3898] Bad request message when switching between two org

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/components/campaigns/Wizard.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step2.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/Step4.jsx
ota-plus-web/app/reactapp/src/components/campaigns/wizardSteps/step2Files/GroupsListItem.jsx
ota-plus-web/app/reactapp/src/components/devices/ContentPanel.jsx
ota-plus-web/app/reactapp/src/components/impactanalysis/BlacklistedPackages.jsx
ota-plus-web/app/reactapp/src/components/profile/Header.jsx
ota-plus-web/app/reactapp/src/components/software/Header.jsx
ota-plus-web/app/reactapp/src/components/software/ListItemVersion.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/containers/Software.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/partials/DependenciesModal.jsx
ota-plus-web/app/reactapp/src/partials/Navigation.jsx
ota-plus-web/app/reactapp/src/partials/NavigationProfile.jsx
ota-plus-web/app/reactapp/src/partials/TabNavigation.jsx
ota-plus-web/app/reactapp/src/stores/FeaturesStore.js

[OTA-4002] Enable feature flags

---

ota-plus-web/app/reactapp/src/components/campaigns/StatisticsDetails.jsx

[OTA-4002] Fix feature flag for campaigns deps

---

ota-plus-web/app/views/authorizationError.scala.html

[OTA-2537] Authorization error page has ATS design

---

ota-plus-web/app/reactapp/src/stores/SoftwareStore.js

[OTA-4047] Confirm button to blacklist packages doesn't function

---

ota-plus-web/docs/modules/ROOT/pages/get-access.adoc

It is not necessary to go the HERE developer portal to sign in, maybe in the future
Resolves OLPSUP-8473

Removed the HERE Developer portal step

---

ota-plus-web/app/reactapp/src/components/profile/access-keys/CreateModal.jsx
ota-plus-web/app/reactapp/src/config.js

[OTA-3851] Provisioning key expiry is changed without informing the user

---

ota-plus-web/app/assets/js/omniture.js
ota-plus-web/app/views/main.scala.html
ota-plus-web/conf/application.conf

[OTA-4077] GDPR pop up

---

ota-plus-web/app/com/advancedtelematic/LoggingFilter.scala

This logs user ip to logs, potentially fulfilling SPC requirement: https://saeljira.it.here.com/browse/OTA-2923

Logs `x-forwarded-for`

---

ota-plus-web/app/reactapp/src/Routes.jsx
ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/partials/Navbar/__tests__/Navbar.spec.js
ota-plus-web/app/reactapp/src/partials/Navbar/index.jsx

[OTA-4215] Flag dashboard

---

ota-plus-web/app/reactapp/src/stores/CampaignsStore.js

[OTA-3981] Viewing campaign dependencies breaks campaign-list views

---

.gitlab-ci.yml

See https://main.gitlab.in.here.com/olp/edge/ota/testing/dynamic-hats

Automatically deploy to EKS cluster

---

ota-plus-web/app/reactapp/src/constants/index.js

[OTA-3939] See the Recent Activity, in the Homepage - fix

---

ota-plus-web/app/reactapp/src/components/device/properties/List.jsx
ota-plus-web/app/reactapp/style/ota-default/pages/_page-device.scss

[OTA-4137] DDV : Install button is broken when disabled

---

ota-plus-web/app/reactapp/src/partials/Footer/index.jsx

[OTA-4103] Review Homepage Pseudo strings in the App - bug fix

---

build.sbt
ota-plus-web/app/com/advancedtelematic/controllers/MetricsController.scala
ota-plus-web/conf/routes

Signed-off-by: koshelev <vladimir.koshelev@here.com>

Add metrics endpoint

---

ota-plus-web/app/reactapp/src/helpers/analyticsHelper.js

[OTA-4338] Fix utag breaking the app

---

ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/constants/urlConstants.js
ota-plus-web/app/reactapp/src/containers/Device.jsx
ota-plus-web/app/reactapp/src/containers/Devices.jsx
ota-plus-web/app/reactapp/src/containers/Software.jsx
ota-plus-web/app/reactapp/src/containers/Terms.jsx
ota-plus-web/app/reactapp/src/containers/Updates.jsx
ota-plus-web/app/reactapp/src/pages/Device.jsx
ota-plus-web/app/reactapp/src/pages/Fireworks.jsx
ota-plus-web/app/reactapp/src/pages/SoftwareRepository.jsx
ota-plus-web/app/reactapp/src/stores/CampaignsStore.js
ota-plus-web/app/reactapp/src/stores/DevicesStore.js
ota-plus-web/app/reactapp/src/stores/GroupsStore.js
ota-plus-web/app/reactapp/src/stores/HardwareStore.js
ota-plus-web/app/reactapp/src/stores/ProvisioningStore.js
ota-plus-web/app/reactapp/src/stores/SoftwareStore.js
ota-plus-web/app/reactapp/src/stores/UpdatesStore.js

[OTA-1833] Remove magic numbers

---

ota-plus-web/app/reactapp/src/components/dashboard/new/DashboardStepper/DashboardStepperCard/__tests__/DashboardStepperCard.spec.js

[OTA-4282] See logical shortcuts in the stepper

---

ota-plus-web/app/assets/locales/en/translation.json
ota-plus-web/app/reactapp/src/containers/Devices.jsx
ota-plus-web/app/reactapp/src/stores/DevicesStore.js

[OTA-4144] When device-registry is down app should show proper message.

---

ota-plus-web/app/reactapp/src/components/profile/EditProfile.jsx
ota-plus-web/app/reactapp/src/components/profile/ProfileOrganization.jsx
ota-plus-web/app/reactapp/src/components/profile/Usage.jsx
ota-plus-web/app/reactapp/src/constants/analyticsViews.js
ota-plus-web/app/reactapp/src/containers/Campaigns.jsx
ota-plus-web/app/reactapp/src/containers/Device.jsx
ota-plus-web/app/reactapp/src/containers/Devices.jsx
ota-plus-web/app/reactapp/src/containers/ImpactAnalysis.jsx
ota-plus-web/app/reactapp/src/containers/Provisioning.jsx
ota-plus-web/app/reactapp/src/containers/Software.jsx
ota-plus-web/app/reactapp/src/containers/Updates.jsx
ota-plus-web/app/reactapp/src/helpers/__tests__/analyticsHelper.spec.js
ota-plus-web/app/reactapp/src/helpers/analyticsHelper.js
ota-plus-web/app/reactapp/src/pages/Home/index.jsx

[OTA-4312] Split the single page in 10 pages in Omniture.

---

ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/stores/DevicesStore.js
ota-plus-web/app/reactapp/src/stores/HardwareStore.js

Use newer director api which director-lite also implements

Feat/ota 4175/director lite

---

ota-plus-web/app/reactapp/src/partials/AccountSidebar/index.jsx

Bugfix - changing environment and logout.

---

ota-plus-web/conf/application.conf

Actual settings can then be done in deployment-descriptors.
Signed-off-by: Jochen Schneider <j.schneider@here.com>

Make http upload configuration configurable through environment vars

---

ota-plus-web/app/reactapp/src/layouts/Main.jsx
ota-plus-web/app/reactapp/src/partials/SubNavBar/index.jsx
ota-plus-web/app/reactapp/style/ota-default/common.scss
ota-plus-web/app/reactapp/style/ota-default/variables-ota.scss

[OTA-4187] Switch environment from anywhere - bug fix 1

---

ota-plus-web/docs/modules/ROOT/nav.adoc
ota-plus-web/docs/modules/ROOT/pages/environments-intro.adoc
ota-plus-web/docs/modules/ROOT/pages/find-and-change-environments.adoc
ota-plus-web/docs/modules/ROOT/pages/manage-members.adoc

Add the Environment section with the following instructions:
* Find environments to which you have access
* Change your active environment
* Add members to environments
* Remove members from environments
Relates-to: OTA-4488

Document existing aspects of the Env feature(beta)

---

ota-plus-web/app/reactapp/src/partials/EnvironmentsSelector/index.jsx
ota-plus-web/app/reactapp/src/partials/EnvironmentsSelector/styled.js
ota-plus-web/app/reactapp/src/partials/SubNavBar/__tests__/SubNavBar.spec.js
ota-plus-web/app/reactapp/src/partials/SubNavBar/index.jsx

[OTA-4548] Switch environment from anywhere - blocking issues

---

ota-plus-web/docs/modules/ROOT/pages/find-and-change-environments.adoc

Modify `find-and-change-environments.adoc` with information on how to
switch to a different environment from anywhere in the portal.
Relates-to: OTA-4585

Add info on how to change env from anywhere

---

ota-plus-web/app/reactapp/package-lock.json
ota-plus-web/app/reactapp/package.json
ota-plus-web/app/reactapp/scripts/createManyDevices.js
ota-plus-web/app/reactapp/src/components/devices/ContentPanel.jsx
ota-plus-web/app/reactapp/src/config.js
ota-plus-web/app/reactapp/src/containers/Devices.jsx
ota-plus-web/app/reactapp/src/pages/Devices.jsx
ota-plus-web/app/reactapp/src/stores/DevicesStore.js
ota-plus-web/app/reactapp/style/ota-default/pages/_page-devices.scss

[OTA-4588] Paginate device list in each group

---

ota-plus-web/app/assets/js/omniture.js

Omniture tag update for JS Script

---

ota-plus-web/app/reactapp/src/components/dashboard/new/RecentActivity/styled.js
ota-plus-web/app/reactapp/src/partials/EnvironmentsSelector/styled.js
ota-plus-web/app/reactapp/src/partials/Footer/styled.js
ota-plus-web/app/reactapp/style/ota-default/pages/_page-devices.scss

Bugfix - devices paging and dropdowns.

---

ota-plus-web/app/reactapp/src/partials/AccountSidebar/index.jsx
ota-plus-web/app/reactapp/src/partials/HelpSidebar/index.jsx
ota-plus-web/app/reactapp/src/partials/Sidebar/index.jsx

Bugfix - sidebar depends on features.

---

ota-plus-web/docs/modules/ROOT/nav.adoc
ota-plus-web/docs/modules/ROOT/pages/get-access.adoc
ota-plus-web/docs/modules/ROOT/pages/index.adoc
ota-plus-web/docs/modules/ROOT/pages/ota-workflow-campaign-manager.adoc

* Review and modify the **Get Started** section of the User guide
and update the navigation page according to the changes.
* Create an instruction on how to get access to the OTA Portal.

Review the **Get Started** section (User Guide)

---

ota-plus-web/app/reactapp/src/components/profile/ProfileOrganization/index.jsx

[OTA-3958] Fix wrong org selected in the list

---

ota-plus-web/docs/modules/ROOT/pages/get-access.adoc
ota-plus-web/docs/modules/ROOT/pages/ota-workflow-campaign-manager.adoc

Modify headings and image size in the **Get started** section of
the User Guide.

Modify headings and image size

---

ota-plus-web/docs/modules/ROOT/nav.adoc
ota-plus-web/docs/modules/ROOT/pages/_partials/devices.adoc
ota-plus-web/docs/modules/ROOT/pages/create-fixed-group.adoc
ota-plus-web/docs/modules/ROOT/pages/create-provisioning-key.adoc
ota-plus-web/docs/modules/ROOT/pages/create-smart-group.adoc
ota-plus-web/docs/modules/ROOT/pages/device-groups.adoc
ota-plus-web/docs/modules/ROOT/pages/manage-device-prov.adoc
ota-plus-web/docs/modules/ROOT/pages/manage-devices.adoc

Modify instructions in the **Devices** section of the User Guide and
the  **Devices** section of the navigation file.

Modify instructions in Devices section(User Guide)

---

ota-plus-web/docs/modules/ROOT/nav.adoc
ota-plus-web/docs/modules/ROOT/pages/blacklist-software.adoc
ota-plus-web/docs/modules/ROOT/pages/campaigns-intro.adoc
ota-plus-web/docs/modules/ROOT/pages/create-campaigns.adoc
ota-plus-web/docs/modules/ROOT/pages/create-update.adoc
ota-plus-web/docs/modules/ROOT/pages/find-and-change-environments.adoc
ota-plus-web/docs/modules/ROOT/pages/manage-members.adoc
ota-plus-web/docs/modules/ROOT/pages/monitor-campaigns.adoc
ota-plus-web/docs/modules/ROOT/pages/updates-intro.adoc
ota-plus-web/docs/modules/ROOT/pages/upload-software-ui.adoc

Review and modify the following 4 sections of the User Guide:
* Software version
* Software updates
* Campaigns
* Environments

Modify 4 sections of the User guide

---

ota-plus-web/app/reactapp/src/utils/WebsocketHandler.js

[OTA-4515] Fix wrong event info in DDV

---

ota-plus-web/docs/modules/ROOT/nav.adoc
ota-plus-web/docs/modules/ROOT/pages/create-environment.adoc
ota-plus-web/docs/modules/ROOT/pages/environments-intro.adoc
ota-plus-web/docs/modules/ROOT/pages/find-and-change-environments.adoc
ota-plus-web/docs/modules/ROOT/pages/manage-members.adoc

Add an instruction on how to create a new environment and update
the Environments section.
Relates-to: OTA-4601

Document how to create an environment

---

ota-plus-web/app/reactapp/src/constants/regexPatterns.js

[OTA-3958] No whitespace allowed

---

ota-plus-web/docs/modules/ROOT/nav.adoc
ota-plus-web/docs/modules/ROOT/pages/use-case-ecm.adoc

Modify the Use Cases section of the User Guide

---

ota-plus-web/docs/modules/ROOT/pages/use-case-ecm.adoc

Correct a typo in the Use Case section
